# Generated by Django 4.2 on 2024-09-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='sobre',
        ),
    ]
