# Generated by Django 4.2 on 2024-09-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria_post_notificacao_comentario_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Posts'},
        ),
    ]
